### ISSUE TITLE
EU consumers lower than EV explode when give any tier of EU with IC2 Classic

### ISSUE THREAD

**Issue by Alleluid** [covers1624/PowerConverters#25]
Not much more to say. Tested with the output of a Batbox.

**Comment by covers1624** [comment]
Ill add a config for now and look in to it further.

**Comment by Speiger** [comment]
@covers1624 that will not work. Classic lets machines that are to low of Power Accepting auto Explode... If you are using tier 0 then it will explode no matter what.

**Comment by covers1624** [comment]
Cheers for the heads up, does ic2 Classic have a different modId to actual ic2?

**Comment by Speiger** [comment]
@covers1624 thats why i have the IC2 + Classic API on github.
And yeah IC2 Classic has his second modID (But other way around will not work because player is not interested/do not see a reason to add a second one).
Here is a link: https://github.com/TinyModularThings/IC2Classic/blob/master/src/main/java/ic2/api/info/IC2Classic.java#L76
But you used the API wrong. The SinkTier function request a tier. Not the Max Eu it supports. 
So Please adjust the numbers from 32, 128, 512, 2048 to 1, 2, 3, 4 (that will be in the enet autoconverted to the numbers you had first).
also if Classic is loaded you do not need to make a explosion because ic2 classic autohandles that, and also if Easy mode is enabled they prevent explosions... Keep that in mind.

**Comment by covers1624** [comment]
Ok so it should be fixed, @Alleluid are you able to try with a build from here http://adel.podgeweb.com:8080/job/Power%20Converters/107/

**Comment by phit** [comment]
crashes on launch for me
[fml-client-3.txt](https://github.com/covers1624/PowerConverters/files/34886/fml-client-3.txt)

**Comment by Speiger** [comment]
@covers1624 ok that looks fine.

**Comment by covers1624** [comment]
@phit you are running the dev version, that is for Deobf development environment, @Speiger Thanks for your help and pointing this out, most of the code is a mess from when i updated it originally.

**Comment by Speiger** [comment]
no problem

**Comment by phit** [comment]
@covers1624 the second url isn't.. here is a new crash with the latest version https://paste.ee/p/NDckx

**Comment by covers1624** [comment]
Just pushed a possible fix for that @phit, should be build 109 on jenkins

**Comment by phit** [comment]
seems to work no more exploding, only issue left is that the bridge ui is missing texture 
![image](https://cloud.githubusercontent.com/assets/2097483/11185987/cd3b1918-8c7f-11e5-8c47-765768f70b0d.png)

**Comment by covers1624** [comment]
can you give me a log please, it contains missing texture info.

**Comment by phit** [comment]
sure, https://paste.ee/p/XE74d

**Comment by covers1624** [comment]
pushing a fix, should be able to from web.

**Comment by phit** [comment]
worked, thanks

**Comment by FinalKill9175** [comment]
Is there an updated version with this fix? Trying to play through tekkit legends but this bug is killing me. Thanks.
